{
  imports = [
    ./control-center.nix
    ./controller.nix
    ./dock.nix
    ./finder.nix
    ./gui.nix
    ./image-capture.nix
    ./keybindings.nix
    ./keyboard.nix
    ./locales.nix
    ./mail.nix
    ./printing.nix
    ./privacy.nix
    ./safari.nix
    ./screencapture.nix
    ./touchpad.nix
  ];
}
